# Generated by Django 5.1.3 on 2024-12-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producthighlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ferbo')),
                ('xlsx', models.FileField(blank=True, null=True, upload_to='ferbo')),
            ],
        ),
    ]
