# Generated by Django 5.1.3 on 2024-12-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ferbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferbo',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
